"""Add travel deals and alerts

Revision ID: 8495efcc0d86
Revises: c92b6eaecdda
Create Date: 2025-11-07 11:07:47.507427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8495efcc0d86'
down_revision = 'c92b6eaecdda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotels_check_in'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_check_out'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_location'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_flights_departure_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('origin', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('airline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('flight_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('flights_pkey'))
    )
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_departure_date'), 'flights', ['departure_date'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('guests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hotels_pkey'))
    )
    op.create_index(op.f('ix_hotels_location'), 'hotels', ['location'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_check_out'), 'hotels', ['check_out'], unique=False)
    op.create_index(op.f('ix_hotels_check_in'), 'hotels', ['check_in'], unique=False)
    # ### end Alembic commands ###