"""Add travel price history table

Revision ID: d460a09e78ac
Revises: 72556645b866
Create Date: 2025-11-14 12:56:56.694312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd460a09e78ac'
down_revision = '72556645b866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_tracked'), table_name='products')
    op.drop_index(op.f('ix_products_site'), table_name='products')
    op.drop_index(op.f('ix_products_url'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_product_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_product_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_table('travel_alert_history')
    op.drop_index(op.f('ix_property_alert_rules_location'), table_name='property_alert_rules')
    op.drop_index(op.f('ix_property_alert_rules_property_id'), table_name='property_alert_rules')
    op.drop_table('property_alert_rules')
    op.drop_index(op.f('ix_hotels_check_in'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_check_out'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_location'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_alert_history_alert_rule_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_product_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_property_alert_history_property_id'), table_name='property_alert_history')
    op.drop_index(op.f('ix_property_alert_history_rule_id'), table_name='property_alert_history')
    op.drop_table('property_alert_history')
    op.drop_index(op.f('ix_property_deals_property_id'), table_name='property_deals')
    op.drop_table('property_deals')
    op.drop_index(op.f('ix_property_price_history_property_id'), table_name='property_price_history')
    op.drop_table('property_price_history')
    op.drop_index(op.f('ix_utility_price_history_service_id'), table_name='utility_price_history')
    op.drop_table('utility_price_history')
    op.drop_index(op.f('ix_utility_services_provider'), table_name='utility_services')
    op.drop_index(op.f('ix_utility_services_service_type'), table_name='utility_services')
    op.drop_table('utility_services')
    op.drop_index(op.f('ix_flights_departure_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_table('flights')
    op.drop_table('travel_alert_rules')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_utility_alert_rules_provider'), table_name='utility_alert_rules')
    op.drop_index(op.f('ix_utility_alert_rules_service_id'), table_name='utility_alert_rules')
    op.drop_index(op.f('ix_utility_alert_rules_service_type'), table_name='utility_alert_rules')
    op.drop_table('utility_alert_rules')
    op.drop_index(op.f('ix_utility_alert_history_rule_id'), table_name='utility_alert_history')
    op.drop_index(op.f('ix_utility_alert_history_service_id'), table_name='utility_alert_history')
    op.drop_table('utility_alert_history')
    op.drop_table('travel_deals')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_utility_deals_service_id'), table_name='utility_deals')
    op.drop_table('utility_deals')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('utility_deals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('deal_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('deal_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['utility_services.id'], name=op.f('utility_deals_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('utility_deals_pkey'))
    )
    op.create_index(op.f('ix_utility_deals_service_id'), 'utility_deals', ['service_id'], unique=False)
    op.create_table('price_history',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('availability', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_history_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_history_pkey'))
    )
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_table('travel_deals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('deal_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('deal_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('travel_deals_flight_id_fkey')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('travel_deals_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('travel_deals_pkey'))
    )
    op.create_table('utility_alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['utility_alert_rules.id'], name=op.f('utility_alert_history_rule_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['utility_services.id'], name=op.f('utility_alert_history_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('utility_alert_history_pkey'))
    )
    op.create_index(op.f('ix_utility_alert_history_service_id'), 'utility_alert_history', ['service_id'], unique=False)
    op.create_index(op.f('ix_utility_alert_history_rule_id'), 'utility_alert_history', ['rule_id'], unique=False)
    op.create_table('utility_alert_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('max_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentage_threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['utility_services.id'], name=op.f('utility_alert_rules_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('utility_alert_rules_pkey'))
    )
    op.create_index(op.f('ix_utility_alert_rules_service_type'), 'utility_alert_rules', ['service_type'], unique=False)
    op.create_index(op.f('ix_utility_alert_rules_service_id'), 'utility_alert_rules', ['service_id'], unique=False)
    op.create_index(op.f('ix_utility_alert_rules_provider'), 'utility_alert_rules', ['provider'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('properties_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_sqm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_per_sqm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('listing_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('agent', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='properties_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_table('travel_alert_rules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('travel_alert_rules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentage_threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name='travel_alert_rules_flight_id_fkey'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='travel_alert_rules_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='travel_alert_rules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('flights',
    sa.Column('origin', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('airline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('flight_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('flights_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='flights_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_departure_date'), 'flights', ['departure_date'], unique=False)
    op.create_table('utility_services',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('utility_services_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('billing_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('plan_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='utility_services_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_utility_services_service_type'), 'utility_services', ['service_type'], unique=False)
    op.create_index(op.f('ix_utility_services_provider'), 'utility_services', ['provider'], unique=False)
    op.create_table('utility_price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tariff_details', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['utility_services.id'], name=op.f('utility_price_history_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('utility_price_history_pkey'))
    )
    op.create_index(op.f('ix_utility_price_history_service_id'), 'utility_price_history', ['service_id'], unique=False)
    op.create_table('property_price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_per_sqm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('listing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('property_price_history_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_price_history_pkey'))
    )
    op.create_index(op.f('ix_property_price_history_property_id'), 'property_price_history', ['property_id'], unique=False)
    op.create_table('property_deals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('deal_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('deal_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('property_deals_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_deals_pkey'))
    )
    op.create_index(op.f('ix_property_deals_property_id'), 'property_deals', ['property_id'], unique=False)
    op.create_table('property_alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('property_alert_history_property_id_fkey')),
    sa.ForeignKeyConstraint(['rule_id'], ['property_alert_rules.id'], name=op.f('property_alert_history_rule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_alert_history_pkey'))
    )
    op.create_index(op.f('ix_property_alert_history_rule_id'), 'property_alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_property_alert_history_property_id'), 'property_alert_history', ['property_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('alert_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trigger_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('alert_history_alert_rule_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('alert_history_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_history_pkey'))
    )
    op.create_index(op.f('ix_alert_history_product_id'), 'alert_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.create_index(op.f('ix_alert_history_alert_rule_id'), 'alert_history', ['alert_rule_id'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('guests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('is_tracked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hotels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hotels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_hotels_location'), 'hotels', ['location'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_check_out'), 'hotels', ['check_out'], unique=False)
    op.create_index(op.f('ix_hotels_check_in'), 'hotels', ['check_in'], unique=False)
    op.create_table('property_alert_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('max_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentage_threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('property_alert_rules_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_alert_rules_pkey'))
    )
    op.create_index(op.f('ix_property_alert_rules_property_id'), 'property_alert_rules', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_alert_rules_location'), 'property_alert_rules', ['location'], unique=False)
    op.create_table('travel_alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['travel_alert_rules.id'], name=op.f('travel_alert_history_alert_rule_id_fkey')),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('travel_alert_history_flight_id_fkey')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('travel_alert_history_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('travel_alert_history_pkey'))
    )
    op.create_table('deals',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deal_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deal_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('deals_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deals_pkey'))
    )
    op.create_index(op.f('ix_deals_product_id'), 'deals', ['product_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentage_threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('alert_rules_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rules_pkey'))
    )
    op.create_index(op.f('ix_alert_rules_product_id'), 'alert_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_tracked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_url'), 'products', ['url'], unique=True)
    op.create_index(op.f('ix_products_site'), 'products', ['site'], unique=False)
    op.create_index(op.f('ix_products_is_tracked'), 'products', ['is_tracked'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###