"""Application constants."""

# Cache TTL (Time To Live) in seconds
CACHE_TTL_USER_DASHBOARD = 180  # 3 minutes
CACHE_TTL_GLOBAL_DASHBOARD = 300  # 5 minutes
CACHE_TTL_ANALYTICS_SAVINGS = 300  # 5 minutes
CACHE_TTL_ANALYTICS_MOST_TRACKED = 600  # 10 minutes
CACHE_TTL_ANALYTICS_RETAILERS = 600  # 10 minutes
CACHE_TTL_ANALYTICS_PRICE_DROPS = 300  # 5 minutes
CACHE_TTL_PRODUCT_ANALYTICS = 300  # 5 minutes
CACHE_TTL_PRICE_HISTORY = 600  # 10 minutes
CACHE_TTL_PRICE_STATS = 300  # 5 minutes
CACHE_TTL_PRICE_TREND = 300  # 5 minutes
